# Generated by Django 5.1 on 2024-09-01 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=100, unique=True)),
                ('handle', models.CharField(blank=True, max_length=100, null=True)),
                ('liver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livers.liver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
