-- データベースの作成
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

-- ユーザーの作成および権限の付与
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
